### PR TITLE
#164798209 User should be able to follow and unfollow each other

### PR DESCRIPTION
**Pull request by felixkiryowa**
#### What does this PR do?

-  Authenticated users should be able to follow and unfollow each other

#### Description of Task to be completed?
-  When a user is authenticated, they should be able to follow and unfollow each other. They should be able to view people that they are following as well as those who follow them.

#### How should this be manually tested?

- Fetch this branch `git fetch origin ft-user-follow-each-164798209`
- Checkout to the branch `git checkout ft-user-follow-each-164798209`
- Run `python manage.py migrate`
- Run `python manage.py runserver`

#### What are the relevant pivotal tracker stories?
[#164798209](https://www.pivotaltracker.com/story/show/164798209)

#### Postman Collection
[Run in Postman](https://app.getpostman.com/run-collection/0b55defca8bf60cb8f00)

### CODE REVIEW

**Review by ja-odur — DISMISSED** [review]
LGTM

**Review by ezrogha — DISMISSED** [review]
LGTM

**Review by dannylwe — CHANGES_REQUESTED** [review]
@felixkiryowa moving forward, kindly do not introduce unnecessary changes (import ordering, adding spaces). Kindly work on your output. If there are other issues you want to be addressed, open a PR or a bug fix. This is the workflow.

You have two commits. Kindly fix this.

**Review by dorothyas — DISMISSED** [review]

**Review by dannylwe — DISMISSED** [review]
LGTM

**Review by ezrogha — CHANGES_REQUESTED** [review]
Good work @felixkiryowa, but
when I tried to check how many followers a user had, 
this is what i received
```
{
    "errors": [
        "You dont have users your following"
    ]
}
```
It is the same message I receive when I check the followers I have
Kindly add a username to this message because it is misleading
also please consider using you're rather than your

**Review by dorothyas — DISMISSED** [review]

**Review by ezrogha — CHANGES_REQUESTED** [review]
Great work with the feedback @felixkiryowa,
Kindly work on the coverage

**Review by ezrogha — DISMISSED** [review]
LGTM

**Review by ja-odur — APPROVED** [review]
LGTM

**Review by dannylwe — APPROVED** [review]
LGTM

**Comment by dorothyas** [comment]
I still think it would be nice to include URLs in your PR description for more clarity,
Otherwise, Great work @felixkiryowa.

**Review by dorothyas — APPROVED** [review]

**Review by ezrogha — APPROVED** [review]

**Pull request merged**
