### PR TITLE
#164798207 Users should be able to comment on articles

### PR DESCRIPTION
**Pull request by felixkiryowa**
#### What does this PR do?

- Enables users receive descriptive error validation messages on signing up

#### Description of Task to be completed?
-  When a user is registering for an account and somehow they don't meet the requirements required for somebody to create an account, then they should be able to get a message as to why they are not able to fulfill their request

#### How should this be manually tested?

- Fetch this branch `git fetch origin ft-comment-on-articles-164798207`
- Checkout to the branch `git checkout  ft-comment-on-articles-164798207`
- Run `python manage.py migrate`
- Run `python manage.py runserver`
- Run `associated endpoints`

#### What are the relevant pivotal tracker stories?
[#164798207](https://www.pivotaltracker.com/story/show/164798207)

#### Postman Collection
[Run in Postman](https://app.getpostman.com/run-collection/da816f8a530014a3e437)

### CODE REVIEW

**Review by dannylwe — COMMENTED** [review]
In your PR, explain how to use your endpoints and the payload the endpoints expect.

**Review by ja-odur — APPROVED** [review]
LGTM

**Review by dorothyas — APPROVED** [review]
Good work

**Review by ezrogha — APPROVED** [review]
Looks good

**Review by dannylwe — APPROVED** [review]

**Pull request merged**
